# Generated by Django 3.1.7 on 2021-04-18 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='view uploaded'),
        ),
    ]
