# Generated by Django 3.1.6 on 2021-02-17 22:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('usr_name', models.CharField(max_length=100)),
                ('usr_username', models.CharField(max_length=20)),
                ('usr_email', models.EmailField(max_length=160)),
                ('usr_password', models.CharField(max_length=200)),
                ('usr_inclasses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), null=True, size=None)),
                ('usr_account_type', models.IntegerField(default=0)),
                ('usr_ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('usr_phone', models.CharField(default='', max_length=15)),
                ('usr_profilepic', models.ImageField(default='profile_pic/user-demo.png', upload_to='profile_pic')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
