# Generated by Django 3.1.6 on 2021-02-13 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='class_db',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50)),
                ('class_createdate', models.DateTimeField(auto_now_add=True)),
                ('class_Discription', models.TextField(null=True)),
                ('class_noofstudents', models.CharField(max_length=50)),
                ('class_limit', models.IntegerField(default=10)),
                ('class_secretkey', models.CharField(default='a3rz-$!p9qneev!7dtf!uzb=(-3xcxt@9ld^wqpf(v*n5*9%j4', max_length=50, unique=True)),
                ('class_cr', models.CharField(default='Select One', max_length=50)),
                ('class_no_of_subjects', models.IntegerField(default=1)),
                ('class_createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
