# Generated by Django 3.1.6 on 2021-02-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_db',
            name='class_image',
            field=models.CharField(default='banner.png', max_length=50),
        ),
    ]
