# Generated by Django 3.1.6 on 2021-02-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_class_db_class_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_db',
            name='class_noofstudents',
            field=models.IntegerField(default=0),
        ),
    ]
