# Generated by Django 3.1.6 on 2021-02-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210213_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_db',
            name='class_secretkey',
            field=models.CharField(default='be1679-6ae28652eb-fa7cd6-de96-a8cc', max_length=50, unique=True),
        ),
    ]
