# Generated by Django 3.1.6 on 2021-02-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210216_1157'),
        ('dashboard', '0005_auto_20210216_1159'),
        ('dashboard', '0005_auto_20210216_1157'),
    ]

    operations = [
    ]
